version: '3'

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    volumes:
      - ./flask:/app
    expose:
      - 5000
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    ports:
      - "8000:8000"

